// GENERATED FILE — do not edit by hand.
// Regenerate with: pnpm vic:localities
//
// Source: https://github.com/matthewproctor/australianpostcodes
// Revision: eda59e4a987d46dbfb1d6bc644a383d322aa3d8d
// Filters: type === "Delivery Area"; status not beginning "Removed"; name not
// ending in a mail-facility code (PO/LPO/DC/MDC/MC/BC); Victorian rows must
// carry a 3xxx or 8xxx postcode.
// Extracted columns: locality, state, postcode. Nothing else from the dataset is
// used. See scripts/generate-vic-localities.ts for provenance and licensing.

/**
 * Every Victorian locality name, normalized by `normalizeLocation`.
 * 3317 entries.
 */
export const VIC_LOCALITIES: ReadonlySet<string> = new Set([
  "abbeyard",
  "abbotsford",
  "aberfeldie",
  "aberfeldy",
  "acheron",
  "ada",
  "adams estate",
  "addington",
  "adelaide lead",
  "agnes",
  "ailsa",
  "aintree",
  "aire valley",
  "aireys inlet",
  "airly",
  "airport west",
  "albacutya",
  "albanvale",
  "albert park",
  "alberton",
  "alberton west",
  "albion",
  "alexandra",
  "alfredton",
  "allambee",
  "allambee reserve",
  "allambee south",
  "allans flat",
  "allansford",
  "allendale",
  "allestree",
  "alma",
  "almonds",
  "almurta",
  "alphington",
  "altona",
  "altona east",
  "altona gate",
  "altona meadows",
  "altona north",
  "alvie",
  "amherst",
  "amor",
  "amphitheatre",
  "anakie",
  "ancona",
  "anderson",
  "angip",
  "anglers rest",
  "anglesea",
  "annuello",
  "antwerp",
  "apollo bay",
  "appin",
  "appin park",
  "appin south",
  "apsley",
  "arapiles",
  "ararat",
  "ararat east",
  "arawata",
  "arbuckle",
  "arcadia",
  "arcadia south",
  "archdale",
  "archdale junction",
  "archerton",
  "archies creek",
  "ardeer",
  "ardmona",
  "areegra",
  "argyle",
  "armadale",
  "armadale north",
  "armstrong",
  "armstrong creek",
  "arnold",
  "arnold west",
  "arthurs creek",
  "arthurs seat",
  "ascot",
  "ascot vale",
  "ashbourne",
  "ashburton",
  "ashwood",
  "aspendale",
  "aspendale gardens",
  "athlone",
  "attwood",
  "aubrey",
  "auburn",
  "auburn south",
  "auchmore",
  "avalon",
  "avenel",
  "avoca",
  "avon plains",
  "avondale heights",
  "avonmore",
  "avonsleigh",
  "axe creek",
  "axedale",
  "ayrford",
  "baarmutha",
  "bacchus marsh",
  "baddaginnie",
  "badger creek",
  "bael bael",
  "bagshot",
  "bagshot north",
  "bahgallah",
  "bailieston",
  "bairnsdale",
  "bakery hill",
  "balaclava",
  "bald hills",
  "bald rock",
  "balintore",
  "ballan",
  "ballangeich",
  "ballapur",
  "ballarat",
  "ballarat central",
  "ballarat east",
  "ballarat north",
  "ballarat roadside delivery",
  "ballarat west",
  "ballendella",
  "balliang",
  "balliang east",
  "ballyrogan",
  "balmattum",
  "balmoral",
  "balnarring",
  "balnarring beach",
  "balook",
  "balwyn",
  "balwyn east",
  "balwyn north",
  "bamawm",
  "bamawm extension",
  "bambra",
  "bamganie",
  "bandiana",
  "bandiana milpo",
  "bangerang",
  "bangholme",
  "banksia peninsula",
  "bannerton",
  "bannockburn",
  "banyan",
  "banyena",
  "banyenong",
  "banyule",
  "baranduda",
  "bareena",
  "barfold",
  "baringhup",
  "baringhup west",
  "barjarg",
  "barkers creek",
  "barkly",
  "barkstead",
  "barmah",
  "barnadown",
  "barnawartha",
  "barnawartha north",
  "baromi",
  "barongarook",
  "barongarook west",
  "barrabool",
  "barrakee",
  "barramunga",
  "barraport",
  "barraport west",
  "barrys reef",
  "barunah park",
  "barunah plains",
  "barwidgee",
  "barwite",
  "barwon downs",
  "barwon heads",
  "basalt",
  "bass",
  "batesford",
  "bathumi",
  "batman",
  "baw baw",
  "baw baw village",
  "baxter",
  "bayindeen",
  "bayles",
  "baynton",
  "baynton east",
  "bayswater",
  "bayswater north",
  "beaconsfield",
  "beaconsfield upper",
  "bealiba",
  "bearii",
  "bears lagoon",
  "beauchamp",
  "beaufort",
  "beaumaris",
  "beazleys bridge",
  "bedford road",
  "beeac",
  "beech forest",
  "beechworth",
  "beenak",
  "belgrave",
  "belgrave heights",
  "belgrave south",
  "bell bird creek",
  "bell park",
  "bell post hill",
  "bellarine",
  "bellbird creek",
  "bellbrae",
  "bellbridge",
  "bellellen",
  "bellfield",
  "bells beach",
  "bellview",
  "belmont",
  "belvedere park",
  "bemm river",
  "ben nevis",
  "bena",
  "benalla",
  "benalla west",
  "benambra",
  "benarch",
  "benayeo",
  "bend of islands",
  "bendigo",
  "bendigo forward",
  "bendigo south",
  "bendoc",
  "bengworden",
  "benjeroop",
  "benloch",
  "bennettswood",
  "bennison",
  "bentleigh",
  "bentleigh east",
  "benwerrin",
  "beremboke",
  "berrambool",
  "berrimal",
  "berrimal west",
  "berringa",
  "berringama",
  "berriwillock",
  "berrybank",
  "berrys creek",
  "berwick",
  "bessiebelle",
  "bet bet",
  "bete bolong",
  "bete bolong north",
  "bethanga",
  "betley",
  "beulah",
  "beverford",
  "beveridge",
  "big desert",
  "big hill",
  "big pats creek",
  "biggara",
  "billabong",
  "bimbourie",
  "bindi",
  "binginwarri",
  "bingo",
  "bingo munjie",
  "birchip",
  "birchip west",
  "birdwoodton",
  "birregurra",
  "bittern",
  "black hill",
  "black range",
  "black rock",
  "black rock north",
  "blackburn",
  "blackburn north",
  "blackburn south",
  "blackheath",
  "blackwarry",
  "blackwood",
  "blackwood forest",
  "blairgowrie",
  "blakeville",
  "blampied",
  "blind bight",
  "blowhard",
  "bo peep",
  "bobinawarrah",
  "bochara",
  "bogong",
  "boho",
  "boho south",
  "boigbeat",
  "boinka",
  "boisdale",
  "bolangum",
  "bolinda",
  "bolton",
  "bolwarra",
  "bolwarrah",
  "bona vista",
  "bonang",
  "bonbeach",
  "bonegilla",
  "boneo",
  "bonn",
  "bonnie brook",
  "bonnie doon",
  "bonshaw",
  "bookaar",
  "boola",
  "boolarong",
  "boolarra",
  "boolarra south",
  "boole poole",
  "boolite",
  "boomahnoomoonah",
  "boonah",
  "boorcan",
  "boorhaman",
  "boorhaman east",
  "boorhaman north",
  "boorolite",
  "boorool",
  "boort",
  "boosey",
  "boralma",
  "bornes hill",
  "boronia",
  "borung",
  "bostocks creek",
  "botanic ridge",
  "boundary bend",
  "bowenvale",
  "boweya",
  "boweya north",
  "bowmans forest",
  "bowser",
  "box hill",
  "box hill central",
  "box hill north",
  "box hill south",
  "boxwood",
  "bradford",
  "bradvale",
  "braeside",
  "branditt",
  "brandon park",
  "brandy creek",
  "branxholme",
  "bravington",
  "braybrook",
  "braybrook north",
  "breakaway creek",
  "breakwater",
  "breamlea",
  "brenanah",
  "brentford square",
  "brewster",
  "briagolong",
  "briar hill",
  "bridge creek",
  "bridge inn",
  "bridgewater",
  "bridgewater north",
  "bridgewater on loddon",
  "bright",
  "brighton",
  "brighton east",
  "brighton north",
  "brighton road",
  "brim",
  "brimboal",
  "brimin",
  "brimpaen",
  "bringalbert",
  "brit brit",
  "broadford",
  "broadlands",
  "broadmeadows",
  "broadwater",
  "brodribb river",
  "broken creek",
  "bromley",
  "brookfield",
  "brooklyn",
  "brookville",
  "broomfield",
  "broughton",
  "brown hill",
  "browns plains",
  "bruarong",
  "bruces creek",
  "brucknell",
  "brumby",
  "brunswick",
  "brunswick east",
  "brunswick lower",
  "brunswick north",
  "brunswick south",
  "brunswick west",
  "bruthen",
  "buangor",
  "buchan",
  "buchan south",
  "buckland",
  "buckley",
  "buckley swamp",
  "buckrabanyule",
  "budgee budgee",
  "budgeree",
  "budgeree east",
  "budgerum east",
  "buffalo",
  "buffalo creek",
  "buffalo river",
  "bulart",
  "buldah",
  "bulga",
  "bulgana",
  "bulla",
  "bullabul",
  "bullaharre",
  "bullarook",
  "bullarto",
  "bullarto south",
  "bulleen",
  "bulleen south",
  "bullengarook",
  "bullioh",
  "bullumwaal",
  "buln buln",
  "buln buln east",
  "bumberrah",
  "bunbartha",
  "bundalaguah",
  "bundalong",
  "bundalong south",
  "bundara",
  "bunding",
  "bundoora",
  "bung bong",
  "bungador",
  "bungal",
  "bungalally",
  "bungaree",
  "bungeet",
  "bungeet west",
  "bungil",
  "bunguluke",
  "buninyong",
  "bunkers hill",
  "bunyip",
  "bunyip north",
  "buragwonduc",
  "burkes bridge",
  "burkes flat",
  "burnbank",
  "burnewang",
  "burnley",
  "burnley north",
  "burnside",
  "burnside heights",
  "burramboot",
  "burramine",
  "burramine south",
  "burrowye",
  "burrumbeet",
  "burwood",
  "burwood east",
  "burwood heights",
  "bushfield",
  "bushy park",
  "butchers ridge",
  "buxton",
  "byaduk",
  "byaduk north",
  "byawatha",
  "byrneside",
  "cabanandra",
  "cabarita",
  "cabbage tree",
  "cabbage tree creek",
  "cadello",
  "cairnlea",
  "calder park",
  "caldermeade",
  "california gully",
  "calivil",
  "callawadda",
  "callignee",
  "callignee north",
  "callignee south",
  "calrossie",
  "calulu",
  "cambarville",
  "camberwell",
  "camberwell east",
  "camberwell north",
  "camberwell south",
  "camberwell west",
  "cambrian hill",
  "campaspe west",
  "campbellfield",
  "campbells bridge",
  "campbells creek",
  "campbells forest",
  "campbelltown",
  "camperdown",
  "canadian",
  "canary island",
  "caniambo",
  "cann river",
  "cannie",
  "cannons creek",
  "cannum",
  "canterbury",
  "cape bridgewater",
  "cape clear",
  "cape conran",
  "cape otway",
  "cape paterson",
  "cape schanck",
  "cape woolamai",
  "capel sound",
  "capels crossing",
  "carag carag",
  "caralulup",
  "caramut",
  "carapooee",
  "carapooee west",
  "carapook",
  "carboor",
  "cardigan",
  "cardigan village",
  "cardinia",
  "cardross",
  "cargerie",
  "carina",
  "caringal",
  "carisbrook",
  "carlisle river",
  "carlsruhe",
  "carlton",
  "carlton north",
  "carlton south",
  "carlyle",
  "carnegie",
  "carngham",
  "caroline springs",
  "carpendeit",
  "carrajung",
  "carrajung lower",
  "carrajung south",
  "carranballac",
  "carron",
  "carrum",
  "carrum downs",
  "carwarp",
  "cashmore",
  "cassilis",
  "castella",
  "casterton",
  "castle creek",
  "castle donnington",
  "castleburn",
  "castlemaine",
  "catani",
  "cathcart",
  "cathkin",
  "catumnal",
  "caulfield",
  "caulfield east",
  "caulfield junction",
  "caulfield north",
  "caulfield south",
  "caveat",
  "cavendish",
  "central park",
  "ceres",
  "chadstone",
  "chadstone centre",
  "chandlers creek",
  "chapel flat",
  "chapel street north",
  "chapple vale",
  "charam",
  "charlemont",
  "charleroi",
  "charlton",
  "chartwell",
  "chatsworth",
  "chelsea",
  "chelsea heights",
  "cheltenham",
  "cheltenham east",
  "cheltenham north",
  "chepstowe",
  "cherokee",
  "cherrilong",
  "cherrypool",
  "cheshunt",
  "cheshunt south",
  "chesney vale",
  "chetwynd",
  "chewton",
  "chewton bushlands",
  "childers",
  "chillingollah",
  "chiltern",
  "chiltern valley",
  "chinangin",
  "chinkapook",
  "chintin",
  "chirnside park",
  "chirrip",
  "chocolyn",
  "christies",
  "christmas hills",
  "chum creek",
  "churchill",
  "churchill island",
  "chute",
  "clarendon",
  "claretown",
  "clarinda",
  "clarkefield",
  "clarkes hill",
  "clayton",
  "clayton south",
  "clear lake",
  "clematis",
  "clifton creek",
  "clifton hill",
  "clifton springs",
  "clonbinane",
  "clover flat",
  "cloverlea",
  "club terrace",
  "clunes",
  "clyde",
  "clyde north",
  "clydebank",
  "clydesdale",
  "coalville",
  "coatesville",
  "cobains",
  "cobaw",
  "cobbannah",
  "cobberas",
  "cobblebank",
  "cobden",
  "cobram",
  "cobram east",
  "cobrico",
  "cobungra",
  "coburg",
  "coburg north",
  "cocamba",
  "cochranes creek",
  "cockatoo",
  "cocoroc",
  "codrington",
  "coghills creek",
  "cohuna",
  "coimadai",
  "cokum",
  "colac",
  "colac colac",
  "colac east",
  "colac west",
  "colbinabbin",
  "colbrook",
  "coldstream",
  "coleraine",
  "colignan",
  "collingwood",
  "collingwood north",
  "colliver",
  "combienbar",
  "comet hill",
  "concongella",
  "condah",
  "condah swamp",
  "congupna",
  "connangorach",
  "connewarre",
  "connewirricoo",
  "coojar",
  "coolaroo",
  "cooma",
  "coomboona",
  "coomoora",
  "coongulla",
  "coonooer bridge",
  "coonooer west",
  "coopers creek",
  "cooriemungle",
  "cope cope",
  "cora lynn",
  "corack",
  "corack east",
  "coragulac",
  "coral bank",
  "corindhap",
  "corinella",
  "corio",
  "corndale",
  "cornelia creek",
  "cornella",
  "cornishtown",
  "coronet bay",
  "corop",
  "corop west",
  "cororooke",
  "corringle",
  "corryong",
  "corunnun",
  "cosgrove",
  "cosgrove south",
  "costerfield",
  "cotham",
  "cotswold",
  "cottles bridge",
  "cowa",
  "cowangie",
  "cowes",
  "cowleys creek",
  "cowwarr",
  "craigie",
  "craigieburn",
  "cranbourne",
  "cranbourne east",
  "cranbourne north",
  "cranbourne south",
  "cranbourne west",
  "creek junction",
  "creek view",
  "creighton",
  "creightons creek",
  "cremorne",
  "cressy",
  "creswick",
  "creswick north",
  "crib point",
  "cromer",
  "crookayan",
  "crooked river",
  "cross keys",
  "cross roads",
  "crossley",
  "crossover",
  "crowlands",
  "croxton east",
  "croydon",
  "croydon hills",
  "croydon north",
  "croydon south",
  "crymelon",
  "crystal creek",
  "cudgee",
  "cudgewa",
  "culgoa",
  "culla",
  "cullen",
  "cullulleraine",
  "cundare",
  "cundare north",
  "curdie vale",
  "curdies river",
  "curdievale",
  "curlewis",
  "curyo",
  "dadswells bridge",
  "dahlen",
  "daisy hill",
  "dales creek",
  "dallas",
  "dalmore",
  "daltons bridge",
  "dalyenong",
  "dalyston",
  "dandenong",
  "dandenong east",
  "dandenong north",
  "dandenong south",
  "dandongadale",
  "dargo",
  "darkbonee",
  "darley",
  "darlimurla",
  "darling",
  "darling south",
  "darlington",
  "darnum",
  "darraweit guim",
  "darriman",
  "dartmoor",
  "dartmouth",
  "dawson",
  "daylesford",
  "deakin university",
  "dean",
  "deans marsh",
  "deanside",
  "deddick valley",
  "dederang",
  "deep creek nsw 2460 corryong",
  "deep lead",
  "deepdene",
  "deer park",
  "deer park east",
  "deer park north",
  "delacombe",
  "delahey",
  "delatite",
  "delburn",
  "delegate river",
  "delegate river east",
  "dellicknora",
  "dendy",
  "denicull creek",
  "denison",
  "dennington",
  "denver",
  "deptford",
  "derby",
  "dereel",
  "dergholm",
  "derrimut",
  "derrinal",
  "derrinallum",
  "devenish",
  "devils river",
  "devon meadows",
  "devon north",
  "dewhurst",
  "dhurringile",
  "diamond creek",
  "diamond hill",
  "digby",
  "diggers rest",
  "diggora",
  "diggora west",
  "dimboola",
  "dingee",
  "dingley village",
  "dingwall",
  "dinner plain",
  "dixie",
  "dixons creek",
  "dobie",
  "docker",
  "dockers plains",
  "docklands",
  "doctors flat",
  "dollar",
  "don valley",
  "donald",
  "doncaster",
  "doncaster east",
  "doncaster heights",
  "donnybrook",
  "donvale",
  "dooboobetic",
  "dooen",
  "dookie",
  "doreen",
  "dorodong",
  "double bridges",
  "douglas",
  "doveton",
  "dreeite",
  "dreeite south",
  "driffield",
  "drik drik",
  "dromana",
  "dropmore",
  "drouin",
  "drouin east",
  "drouin south",
  "drouin west",
  "drumanure",
  "drumborg",
  "drumcondra",
  "drummartin",
  "drummond",
  "drummond north",
  "drung",
  "dry diggings",
  "drysdale",
  "duchembegarra",
  "dugays bridge",
  "dumbalk",
  "dumbalk north",
  "dumosa",
  "dunach",
  "dundonnell",
  "dunearn",
  "dunkeld",
  "dunkirk",
  "dunluce",
  "dunneworthy",
  "dunnstown",
  "dunolly",
  "dunrobin",
  "durdidwarrah",
  "durham lead",
  "durham ox",
  "dutson",
  "dutson downs",
  "dutton way",
  "duverney",
  "dysart",
  "eagle point",
  "eaglehawk",
  "eaglehawk north",
  "eaglemont",
  "earlston",
  "east bairnsdale",
  "east bendigo",
  "east geelong",
  "east melbourne",
  "east sale",
  "east sale raaf",
  "east wangaratta",
  "east warburton",
  "east yeoburn",
  "eastern view",
  "eastville",
  "eastwood",
  "ebden",
  "echuca",
  "echuca east",
  "echuca south",
  "echuca village",
  "echuca west",
  "ecklin south",
  "eddington",
  "eden park",
  "edenhope",
  "edgecombe",
  "edi",
  "edi upper",
  "edithvale",
  "eganstown",
  "eildon",
  "elaine",
  "elberton",
  "eldorado",
  "elevated plains",
  "elingamite",
  "elingamite north",
  "elizabeth island",
  "ellaswood",
  "ellerslie",
  "elliminyt",
  "ellinbank",
  "elmhurst",
  "elmore",
  "elphinstone",
  "elsternwick",
  "eltham",
  "eltham north",
  "elwood",
  "emerald",
  "emu",
  "emu creek",
  "emu flat",
  "endeavour hills",
  "enfield",
  "englefield",
  "enochs point",
  "ensay",
  "ensay north",
  "eppalock",
  "epping",
  "epsom",
  "ercildoune",
  "erica",
  "errinundra",
  "eskdale",
  "esmond",
  "essendon",
  "essendon fields",
  "essendon north",
  "essendon west",
  "eumemmerring",
  "eurack",
  "eureka",
  "euroa",
  "eurobin",
  "evansford",
  "eversley",
  "everton",
  "everton upper",
  "exford",
  "eynesbury",
  "fairbank",
  "fairfield",
  "fairhaven",
  "fairley",
  "fairy dell",
  "falls creek",
  "faraday",
  "fawcett",
  "fawkner",
  "fawkner east",
  "fawkner north",
  "fentons creek",
  "ferguson",
  "fern hill",
  "fernbank",
  "ferndale",
  "fernihurst",
  "fernshaw",
  "ferntree gully",
  "fernvale",
  "ferny creek",
  "fieldstone",
  "fiery flat",
  "fingal",
  "fish creek",
  "fish point",
  "fiskville",
  "fitzroy",
  "fitzroy north",
  "five ways",
  "flaggy creek",
  "flagstaff",
  "flamingo beach",
  "flemington",
  "flinders",
  "flora hill",
  "flowerdale",
  "flynn",
  "flynns creek",
  "footscray",
  "forbes",
  "forest hill",
  "forge creek",
  "forrest",
  "foster",
  "foster north",
  "fosterville",
  "fountain gate",
  "foxhow",
  "framlingham",
  "framlingham east",
  "franklinford",
  "frankston",
  "frankston east",
  "frankston heights",
  "frankston north",
  "frankston south",
  "fraser rise",
  "freeburgh",
  "french island",
  "frenchmans",
  "freshwater creek",
  "fryerstown",
  "fulham",
  "fumina",
  "fumina south",
  "fyans creek",
  "fyansford",
  "gaffneys creek",
  "gainsborough",
  "gannawarra",
  "gapsted",
  "garden city",
  "gardenvale",
  "garfield",
  "garfield north",
  "garibaldi",
  "garvoc",
  "gateway island",
  "gatum",
  "gazette",
  "geelong",
  "geelong north",
  "geelong west",
  "gelantipy",
  "gellibrand",
  "gellibrand lower",
  "gelliondale",
  "gembrook",
  "genoa",
  "gentle annie",
  "georges creek",
  "gerahmin",
  "gerang gerung",
  "gerangamete",
  "germania",
  "germantown",
  "gerrigerrup",
  "gherang",
  "gheringhap",
  "ghin ghin",
  "giffard",
  "giffard west",
  "gil gil",
  "gilberton",
  "gilderoy",
  "gillieston",
  "gillum",
  "gipsy point",
  "girgarre",
  "girgarre east",
  "gisborne",
  "gisborne south",
  "gladfield",
  "gladstone park",
  "gladysdale",
  "glen alvie",
  "glen creek",
  "glen falloch",
  "glen forbes",
  "glen huntly",
  "glen iris",
  "glen park",
  "glen valley",
  "glen waverley",
  "glen wills",
  "glenaire",
  "glenaladale",
  "glenalbyn",
  "glenaroua",
  "glenbrae",
  "glenburn",
  "glendaruel",
  "glendonald",
  "glendonnell",
  "glenfalloch",
  "glenferrie south",
  "glenfyne",
  "glengala",
  "glengarry",
  "glengarry north",
  "glengarry west",
  "glengower",
  "glenhope",
  "glenhope east",
  "glenisla",
  "glenlee",
  "glenlofty",
  "glenlogie",
  "glenloth",
  "glenloth east",
  "glenluce",
  "glenlyon",
  "glenmaggie",
  "glenmore",
  "glenorchy",
  "glenormiston",
  "glenormiston north",
  "glenormiston south",
  "glenpatrick",
  "glenrowan",
  "glenrowan west",
  "glenroy",
  "glenthompson",
  "glomar beach",
  "gnarwarre",
  "gnotuk",
  "gobarup",
  "gobur",
  "golden beach",
  "golden gully",
  "golden point",
  "golden square",
  "goldie",
  "goldsborough",
  "gong gong",
  "gonn crossing",
  "goomalibee",
  "goon nure",
  "goongerah",
  "gooram",
  "gooramadda",
  "goorambat",
  "goornong",
  "gooroc",
  "gorae",
  "gorae west",
  "gordon",
  "gormandale",
  "goroke",
  "goschen",
  "goughs bay",
  "goulburn weir",
  "gowanbrae",
  "gowanford",
  "gowangardie",
  "gowar east",
  "gower",
  "grahamvale",
  "grampians",
  "grand ridge",
  "grangefields",
  "granite flat",
  "granite rock",
  "grantville",
  "granya",
  "grass flat",
  "grassdale",
  "grassmere",
  "grassy spur",
  "grays bridge",
  "graytown",
  "gre gre",
  "gre gre north",
  "gre gre south",
  "great southern",
  "great western",
  "gredgwin",
  "green gully",
  "green lake",
  "greendale",
  "greenhill",
  "greens creek",
  "greensborough",
  "greenvale",
  "greenwald",
  "grenville",
  "greta",
  "greta south",
  "greta west",
  "grey river",
  "greythorn",
  "gringegalgona",
  "gritjurk",
  "grovedale",
  "grovedale east",
  "gruyere",
  "guildford",
  "gunbower",
  "gundowring",
  "gunyah",
  "guthridge",
  "guys forest",
  "guys hill",
  "gymbowen",
  "haddon",
  "hadfield",
  "hallam",
  "hallora",
  "halls gap",
  "hallston",
  "hamilton",
  "hamlyn heights",
  "hampton",
  "hampton east",
  "hampton north",
  "hampton park",
  "hanging rock",
  "hansonville",
  "happy valley",
  "harcourt",
  "harcourt north",
  "harkaway",
  "harkness",
  "harmers haven",
  "harrietville",
  "harrow",
  "harston",
  "hartwell",
  "hastings",
  "hattah",
  "havelock",
  "haven",
  "havilah",
  "havillah",
  "hawkesdale",
  "hawkhurst",
  "hawksburn",
  "hawthorn",
  "hawthorn east",
  "hawthorn north",
  "hawthorn west",
  "haydens bog",
  "hazel park",
  "hazeldene",
  "hazelwood",
  "hazelwood north",
  "hazelwood south",
  "healesville",
  "healesville main street",
  "healesville post shop",
  "heath field",
  "heath hill",
  "heathcote",
  "heathcote junction",
  "heathcote south",
  "heatherton",
  "heathmere",
  "heathmont",
  "heathwood",
  "hedley",
  "heidelberg",
  "heidelberg heights",
  "heidelberg rgh",
  "heidelberg west",
  "hensley park",
  "henty",
  "hepburn",
  "hepburn springs",
  "herne hill",
  "hernes oak",
  "hesket",
  "hesse",
  "hexham",
  "heyfield",
  "heytesbury lower",
  "heywood",
  "hiamdale",
  "hiawatha",
  "hicksborough",
  "hidden valley",
  "high camp",
  "highett",
  "highlands",
  "highpoint city",
  "highton",
  "hilgay",
  "hill end",
  "hillcrest",
  "hilldene",
  "hillside",
  "hinnomunjie",
  "hoddle",
  "hoddles creek",
  "hollands landing",
  "holmesglen",
  "homebush",
  "homerton",
  "homewood",
  "hopetoun",
  "hopetoun gardens",
  "hopetoun park",
  "hopevale",
  "hoppers crossing",
  "hordern vale",
  "horfield",
  "horsham",
  "horsham west",
  "hotham heights",
  "hotham hill",
  "hotspur",
  "houston",
  "howes creek",
  "howitt plains",
  "howqua",
  "howqua hills",
  "howqua inlet",
  "hughesdale",
  "hume weir",
  "humevale",
  "hunter",
  "hunterston",
  "huntingdale",
  "huntly",
  "huntly north",
  "huon",
  "huon creek",
  "hurdle flat",
  "hurstbridge",
  "icy creek",
  "iguana creek",
  "illabarook",
  "illawarra",
  "illowa",
  "indented head",
  "indigo",
  "indigo upper",
  "indigo valley",
  "inglewood",
  "ingliston",
  "inkerman",
  "invergordon",
  "invergordon south",
  "inverleigh",
  "inverloch",
  "invermay",
  "invermay park",
  "iona",
  "iraak",
  "irishtown",
  "ironbark",
  "irrewarra",
  "irrewillipe",
  "irrewillipe east",
  "irymple",
  "ivanhoe",
  "ivanhoe east",
  "ivanhoe north",
  "jacana",
  "jack river",
  "jackass flat",
  "jacob creek",
  "jallakin",
  "jallukur",
  "jallumba",
  "jam jerrup",
  "jamieson",
  "jan juc",
  "jancourt",
  "jancourt east",
  "jarklin",
  "jarrahmond",
  "jarvis creek",
  "jeeralang",
  "jeeralang junction",
  "jeetho",
  "jeffcott",
  "jeffcott north",
  "jeparit",
  "jericho",
  "jeruk",
  "jil jil",
  "jilpanger",
  "jindivick",
  "joel joel",
  "joel south",
  "johanna",
  "johnsonville",
  "johnstones hill",
  "jordanville",
  "joyces creek",
  "jumbuk",
  "jumbunna",
  "junction village",
  "jung",
  "jungaburra",
  "junortoun",
  "kaarimba",
  "kadnook",
  "kalimna",
  "kalimna west",
  "kalkallo",
  "kalkee",
  "kallista",
  "kalorama",
  "kalpienung",
  "kamarooka",
  "kamarooka north",
  "kanagulk",
  "kancoona",
  "kancoona south",
  "kangaroo flat",
  "kangaroo ground",
  "kaniva",
  "kanumbra",
  "kanya",
  "kanyapella",
  "karabeal",
  "kardella",
  "kardella south",
  "kariah",
  "karingal",
  "karingal centre",
  "karnak",
  "karramomus",
  "karyrie",
  "katamatite",
  "katamatite east",
  "katandra",
  "katandra west",
  "katunga",
  "kawarren",
  "kealba",
  "keely",
  "keilor",
  "keilor downs",
  "keilor east",
  "keilor lodge",
  "keilor north",
  "keilor park",
  "kellalac",
  "kelvin view",
  "kenley",
  "kenmare",
  "kennedys creek",
  "kennett river",
  "kennington",
  "kensington",
  "keon park",
  "kerang",
  "kerang east",
  "kergunyah",
  "kergunyah south",
  "kernot",
  "kerrie",
  "kerrimuir",
  "kerrisdale",
  "kevington",
  "kew",
  "kew east",
  "kewell",
  "keysborough",
  "kialla",
  "kialla east",
  "kialla west",
  "kiata",
  "kiewa",
  "kilcunda",
  "kilfeera",
  "killara",
  "killarney",
  "killawarra",
  "killingworth",
  "kilmany",
  "kilmore",
  "kilmore east",
  "kilsyth",
  "kilsyth south",
  "kimbolton",
  "king valley",
  "kinglake",
  "kinglake central",
  "kinglake west",
  "kingower",
  "kings park",
  "kingsbury",
  "kingston",
  "kingsville",
  "kingsville west",
  "kinnabulla",
  "kinypanial",
  "kirkstall",
  "kirwans bridge",
  "kithbrook",
  "knebsworth",
  "knockwood",
  "knowsley",
  "knox city centre",
  "knoxfield",
  "koallah",
  "kobyboyn",
  "koetong",
  "kolora",
  "kongwak",
  "konongwootong",
  "koo wee rup",
  "koo wee rup north",
  "kooloonong",
  "koonda",
  "koondrook",
  "koonoomoo",
  "koonwarra",
  "kooreh",
  "koorlong",
  "koornalla",
  "kooroocheang",
  "koorool",
  "koorooman",
  "kooyong",
  "koriella",
  "korobeit",
  "koroit",
  "korong vale",
  "koroop",
  "korrine",
  "korumburra",
  "korumburra south",
  "korweinguboora",
  "kotta",
  "kotupna",
  "koyuga",
  "koyuga south",
  "krowera",
  "kulwin",
  "kunat",
  "kunyung",
  "kurraca",
  "kurraca west",
  "kurting",
  "kurunjang",
  "ky valley",
  "ky west",
  "kyabram",
  "kyabram south",
  "kyneton",
  "kyneton south",
  "kyvalley",
  "la trobe university",
  "laanecoorie",
  "laang",
  "labertouche",
  "laburnum",
  "laceby",
  "ladys pass",
  "laen",
  "laen east",
  "laen north",
  "lah",
  "laharum",
  "lake boga",
  "lake bolac",
  "lake buloke",
  "lake bunga",
  "lake charm",
  "lake condah",
  "lake eildon",
  "lake eppalock",
  "lake fyans",
  "lake gardens",
  "lake goldsmith",
  "lake hindmarsh",
  "lake lonsdale",
  "lake marmal",
  "lake meran",
  "lake mokoan",
  "lake moodemere",
  "lake mundi",
  "lake powell",
  "lake rowan",
  "lake tyers",
  "lake tyers beach",
  "lake tyrrell",
  "lake wellington",
  "lake wendouree",
  "lake wongan",
  "lakes entrance",
  "lal lal",
  "lalbert",
  "lalor",
  "lalor plaza",
  "lamplough",
  "lancaster",
  "lance creek",
  "lancefield",
  "landsborough",
  "landsborough west",
  "lang lang",
  "lang lang east",
  "langdons hill",
  "langi kal kal",
  "langi logan",
  "langkoop",
  "langley",
  "langsborough",
  "langwarrin",
  "langwarrin south",
  "lansell plaza",
  "lara",
  "lardner",
  "larpent",
  "larralea",
  "lascelles",
  "launching place",
  "lauriston",
  "lavers hill",
  "laverton",
  "laverton north",
  "laverton raaf",
  "lawler",
  "lawloit",
  "lawrence",
  "leaghur",
  "learmonth",
  "ledcourt",
  "leichardt",
  "leigh creek",
  "leitchville",
  "lemnos",
  "leneva",
  "leonards hill",
  "leongatha",
  "leongatha north",
  "leongatha south",
  "leopold",
  "lerderderg",
  "leslie manor",
  "lethbridge",
  "lexton",
  "licola",
  "licola north",
  "lillico",
  "lillicur",
  "lillimur",
  "lilliput",
  "lilydale",
  "lima",
  "lima east",
  "lima south",
  "limestone",
  "limonite",
  "lindenow",
  "lindenow south",
  "lindsay",
  "lindsay point",
  "linga",
  "linton",
  "liparoo",
  "lismore",
  "litchfield",
  "little desert",
  "little hampton",
  "little river",
  "llanelly",
  "llowalong",
  "loch",
  "loch sport",
  "loch valley",
  "lochend",
  "lockington",
  "locksley",
  "lockwood",
  "lockwood south",
  "loddon vale",
  "logan",
  "londrigan",
  "lone pine",
  "long forest",
  "long gully",
  "longerenong",
  "longford",
  "longlea",
  "longwarry",
  "longwarry north",
  "longwood",
  "longwood east",
  "lorne",
  "lorquon",
  "lovely banks",
  "lower moira",
  "lower norton",
  "lower plenty",
  "loy yang",
  "lubeck",
  "lucas",
  "lucknow",
  "lucyvale",
  "lurg",
  "lyal",
  "lygon street north",
  "lynbrook",
  "lyndale",
  "lyndhurst",
  "lyons",
  "lyonville",
  "lysterfield",
  "lysterfield south",
  "macarthur",
  "macclesfield",
  "macedon",
  "macks creek",
  "macleod",
  "macleod west",
  "macorna",
  "macorna north",
  "macs cove",
  "madalya",
  "maddingley",
  "mafeking",
  "maffra",
  "maffra west upper",
  "magpie",
  "maiden gully",
  "maidstone",
  "mailer flat",
  "mailors flat",
  "main lead",
  "main ridge",
  "maindample",
  "maintongoon",
  "major plains",
  "majorca",
  "maldon",
  "mallacoota",
  "malmsbury",
  "malvern",
  "malvern east",
  "malvern north",
  "mambourin",
  "manangatang",
  "mandurang",
  "mandurang south",
  "mangalore",
  "manifold heights",
  "mannerim",
  "mannibadar",
  "manns beach",
  "manor lakes",
  "manorina",
  "mansfield",
  "maramingo creek",
  "marcus hill",
  "mardan",
  "marengo",
  "maribyrnong",
  "marionvale",
  "markwood",
  "marlbed",
  "marlo",
  "marnoo",
  "marnoo east",
  "marnoo west",
  "marong",
  "maroona",
  "marraweeney",
  "marshall",
  "marthavale",
  "martins creek",
  "marungi",
  "maryborough",
  "maryknoll",
  "marysville",
  "maryvale",
  "massey",
  "matlock",
  "maude",
  "mayreef",
  "mccrae",
  "mcevoys",
  "mcintyre",
  "mckenzie creek",
  "mckenzie hill",
  "mckinnon",
  "mcloughlins beach",
  "mcmahons creek",
  "mcmillans",
  "mead",
  "meadow creek",
  "meadow heights",
  "meatian",
  "medlyn",
  "meeniyan",
  "meereek",
  "meering west",
  "meerlieu",
  "melbourne",
  "melbourne airport",
  "melbourne university",
  "melton",
  "melton south",
  "melton west",
  "melville forest",
  "melwood",
  "mena park",
  "mentone",
  "mentone east",
  "menzies creek",
  "mepunga",
  "mepunga east",
  "mepunga west",
  "merbein",
  "merbein south",
  "merbein west",
  "meredith",
  "meringur",
  "merino",
  "merlynston",
  "mernda",
  "merriang",
  "merriang south",
  "merricks",
  "merricks beach",
  "merricks north",
  "merrigum",
  "merrijig",
  "merrimu",
  "merrinee",
  "merton",
  "metcalfe",
  "metcalfe east",
  "metung",
  "mewburn park",
  "mia mia",
  "mickleham",
  "mid valley",
  "middle camberwell",
  "middle creek",
  "middle park",
  "middle tarwin",
  "miepoll",
  "miga lake",
  "milawa",
  "mildura",
  "mildura centre plaza",
  "mildura east",
  "mildura south",
  "mildura west",
  "mill park",
  "millbrook",
  "millgrove",
  "milloo",
  "milltown",
  "milnes bridge",
  "mincha",
  "mincha west",
  "miners rest",
  "mingay",
  "minhamite",
  "minimay",
  "mininera",
  "minjah",
  "minmindie",
  "minto",
  "minyip",
  "miowera",
  "miralie",
  "miram",
  "mirboo",
  "mirboo east",
  "mirboo north",
  "mirboo south",
  "mirimbah",
  "mirranatwa",
  "mitcham",
  "mitcham north",
  "mitchell park",
  "mitchells hill",
  "mitchellstown",
  "mitiamo",
  "mitre",
  "mitta mitta",
  "mittyack",
  "mockinya",
  "modella",
  "modewarre",
  "moe",
  "moe south",
  "moggs creek",
  "moglonemby",
  "mokepilly",
  "molesworth",
  "moliagul",
  "molka",
  "mollongghip",
  "mologa",
  "molyullah",
  "monash university",
  "monbulk",
  "mongans bridge",
  "monomak",
  "monomeith",
  "mont albert",
  "mont albert north",
  "montgomery",
  "montmorency",
  "montrose",
  "moolap",
  "moolerr",
  "moolort",
  "moonambel",
  "moondarra",
  "moonee ponds",
  "moonee vale",
  "moonlight flat",
  "moora",
  "moorabbin",
  "moorabbin airport",
  "moorabbin east",
  "moorabool",
  "mooralla",
  "moorilim",
  "moormbool west",
  "moornapa",
  "moorngag",
  "moorooduc",
  "mooroolbark",
  "mooroopna",
  "mooroopna north",
  "mooroopna north west",
  "moranding",
  "morang south",
  "mordialloc",
  "mordialloc north",
  "moreland",
  "moreland west",
  "morgiana",
  "moriac",
  "mornington",
  "moroka",
  "morrisons",
  "morrl morrl",
  "mortchup",
  "mortlake",
  "morton plains",
  "morwell",
  "morwell east",
  "morwell upper",
  "mosquito creek",
  "mossiface",
  "mount alfred",
  "mount beauty",
  "mount beckworth",
  "mount best",
  "mount bolton",
  "mount bruno",
  "mount buffalo",
  "mount buller",
  "mount burnett",
  "mount bute",
  "mount camel",
  "mount cameron",
  "mount clear",
  "mount cole",
  "mount cole creek",
  "mount cottrell",
  "mount dandenong",
  "mount doran",
  "mount dryden",
  "mount duneed",
  "mount eccles",
  "mount eccles south",
  "mount egerton",
  "mount eliza",
  "mount emu",
  "mount evelyn",
  "mount franklin",
  "mount glasgow",
  "mount helen",
  "mount hooghly",
  "mount hotham",
  "mount lonarch",
  "mount macedon",
  "mount major",
  "mount martha",
  "mount mercer",
  "mount mitchell",
  "mount moriac",
  "mount napier",
  "mount pleasant",
  "mount prospect",
  "mount richmond",
  "mount rowan",
  "mount sabine",
  "mount scobie",
  "mount slide",
  "mount tassie",
  "mount taylor",
  "mount toolebewong",
  "mount wallace",
  "mount waverley",
  "mountain bay",
  "mountain gate",
  "mountain view",
  "moutajup",
  "moyarra",
  "moyhu",
  "moyreisk",
  "moyston",
  "mt baw baw",
  "muckatah",
  "muckleford",
  "muckleford south",
  "mudgegonga",
  "mulgrave",
  "mumbannar",
  "mundoona",
  "munro",
  "muntham",
  "murchison",
  "murchison east",
  "murchison north",
  "murgheboluc",
  "murmungee",
  "murnungin",
  "murphys creek",
  "murra warra",
  "murrabit",
  "murrabit west",
  "murrawee",
  "murray lock no 9",
  "murray sunset",
  "murraydale",
  "murrayville",
  "murrindal",
  "murrindindi",
  "murroon",
  "murrumbeena",
  "murtoa",
  "musk",
  "musk vale",
  "muskerry",
  "muskerry east",
  "myall",
  "myamyn",
  "myers flat",
  "myola",
  "myola east",
  "myrniong",
  "myrrhee",
  "myrtle creek",
  "myrtlebank",
  "myrtleford",
  "mysia",
  "mystic park",
  "mywee",
  "nagambie",
  "nalangil",
  "nalinga",
  "nambrok",
  "nandaly",
  "nangana",
  "nangeela",
  "nangiloc",
  "nanneella",
  "nap nap marra",
  "napoleons",
  "nar nar goon",
  "nar nar goon north",
  "narbethong",
  "nareeb",
  "nareen",
  "nareewillock",
  "nariel valley",
  "naring",
  "naringal",
  "naringal east",
  "naroghid",
  "narracan",
  "narraport",
  "narrapumelap south",
  "narrawong",
  "narre warren",
  "narre warren east",
  "narre warren north",
  "narre warren south",
  "narrung",
  "nathalia",
  "natimuk",
  "natte yallock",
  "natya",
  "navarre",
  "navigators",
  "nayook",
  "neds corner",
  "neereman",
  "neerim",
  "neerim east",
  "neerim junction",
  "neerim north",
  "neerim south",
  "neilborough",
  "nelse",
  "nelson",
  "nerrena",
  "nerrin nerrin",
  "nerrina",
  "nerring",
  "netherby",
  "neuarpurr",
  "new gisborne",
  "newborough",
  "newborough east",
  "newbridge",
  "newbury",
  "newcomb",
  "newfield",
  "newham",
  "newhaven",
  "newington",
  "newlands arm",
  "newlyn",
  "newlyn north",
  "newmerella",
  "newport",
  "newry",
  "newstead",
  "newtown",
  "nhill",
  "nichols point",
  "nicholson",
  "niddrie",
  "niddrie north",
  "nillahcootie",
  "nilma",
  "nilma north",
  "ninda",
  "nine mile",
  "nintingbool",
  "ninyeunook",
  "nirranda",
  "nirranda east",
  "nirranda south",
  "noble park",
  "noble park east",
  "noble park north",
  "noojee",
  "noorat",
  "noorat east",
  "noorinbee",
  "noorinbee north",
  "noradjuha",
  "norlane",
  "normanville",
  "norong",
  "norong central",
  "north bendigo",
  "north blackwood",
  "north geelong",
  "north melbourne",
  "north road",
  "north shore",
  "north wangaratta",
  "north warrandyte",
  "north wonthaggi",
  "northcote",
  "northcote south",
  "northland centre",
  "northwood",
  "norval",
  "notting hill",
  "nowa nowa",
  "nowhere creek",
  "nowie",
  "nug nug",
  "nuggetty",
  "nulla vale",
  "nullawarre",
  "nullawarre east",
  "nullawarre north",
  "nullawil",
  "numurkah",
  "nunawading",
  "nungurner",
  "nunniong",
  "nuntin",
  "nurcoung",
  "nurrabiel",
  "nurran",
  "nutfield",
  "nyah",
  "nyah west",
  "nyarrin",
  "nyerimilang",
  "nyora",
  "nyrraby",
  "oak park",
  "oaklands junction",
  "oakleigh",
  "oakleigh east",
  "oakleigh south",
  "oakvale",
  "ocean grange",
  "ocean grove",
  "officer",
  "officer south",
  "old tallangatta",
  "olinda",
  "ombersley",
  "omeo",
  "omeo valley",
  "ondit",
  "orbost",
  "orford",
  "ormond",
  "orrvale",
  "osbornes flat",
  "outtrim",
  "ouyen",
  "ovens",
  "oxley",
  "oxley flats",
  "ozenkadnook",
  "paaratte",
  "painswick",
  "pakenham",
  "pakenham south",
  "pakenham upper",
  "panitya",
  "panmure",
  "panton hill",
  "paradise",
  "paradise beach",
  "paraparap",
  "park orchards",
  "parkdale",
  "parkville",
  "parkwood",
  "parwan",
  "paschendale",
  "pascoe vale",
  "pascoe vale south",
  "pastoria",
  "pastoria east",
  "patchewollock",
  "patho",
  "patho west",
  "patterson",
  "patterson lakes",
  "patyah",
  "paynesville",
  "pearcedale",
  "pearsondale",
  "peechelba",
  "peechelba east",
  "pelluebla",
  "pennyroyal",
  "penshurst",
  "pental island",
  "pentland hills",
  "percydale",
  "perkins reef",
  "peronne",
  "perry bridge",
  "peterborough",
  "petticoat creek",
  "pheasant creek",
  "piangil",
  "piavella",
  "picola",
  "picola west",
  "piedmont",
  "pier milan",
  "pigeon ponds",
  "piggoreet",
  "pilchers bridge",
  "pimpinio",
  "pine grove",
  "pine grove east",
  "pine lodge",
  "pine mountain",
  "pine view",
  "pines forest",
  "pinewood",
  "pioneer bay",
  "pipers creek",
  "pira",
  "piries",
  "pirron yallock",
  "pitfield",
  "pittong",
  "plenty",
  "plumpton",
  "point cook",
  "point leo",
  "point lonsdale",
  "point wilson",
  "polisbet",
  "pomborneit",
  "pomborneit east",
  "pomborneit north",
  "pomonal",
  "pompapiel",
  "poolaijelo",
  "pootilla",
  "poowong",
  "poowong east",
  "poowong north",
  "porcupine flat",
  "porcupine ridge",
  "porepunkah",
  "port albert",
  "port campbell",
  "port fairy",
  "port franklin",
  "port melbourne",
  "port welshpool",
  "portarlington",
  "portland",
  "portland north",
  "portland west",
  "portsea",
  "pound creek",
  "powelltown",
  "powers creek",
  "powlett plains",
  "powlett river",
  "prahran",
  "prahran east",
  "prairie",
  "pranjip",
  "prentice north",
  "preston",
  "preston lower",
  "preston south",
  "preston west",
  "princes hill",
  "princetown",
  "puckapunyal",
  "puckapunyal milpo",
  "pura pura",
  "puralka",
  "purdeet",
  "purnim",
  "purnim west",
  "pyalong",
  "pyramid hill",
  "quambatook",
  "quandong",
  "quantong",
  "quarry hill",
  "queenscliff",
  "queensferry",
  "raglan",
  "rainbow",
  "ranceby",
  "rangeview",
  "rathscar",
  "rathscar west",
  "ravenhall",
  "ravenswood",
  "ravenswood south",
  "rawson",
  "raymond island",
  "raywood",
  "red bluff",
  "red cliffs",
  "red hill",
  "red hill south",
  "red lion",
  "redan",
  "redbank",
  "redcastle",
  "redesdale",
  "reedy creek",
  "reedy dam",
  "reedy flat",
  "reedy lake",
  "reefton",
  "regent west",
  "remlaw",
  "research",
  "reservoir",
  "reservoir east",
  "reservoir north",
  "reservoir south",
  "reynard",
  "rheola",
  "rhyll",
  "rhymney",
  "riachella",
  "rich avon",
  "rich avon east",
  "rich avon west",
  "richmond",
  "richmond east",
  "richmond north",
  "richmond plains",
  "richmond south",
  "riddells creek",
  "riggs creek",
  "ringwood",
  "ringwood east",
  "ringwood north",
  "ripplebrook",
  "rippleside",
  "ripponhurst",
  "ripponlea",
  "riverside",
  "riverslea",
  "robertsons beach",
  "robinson",
  "robinvale",
  "robinvale irrigation district section b",
  "robinvale irrigation district section c",
  "robinvale irrigation district section d",
  "robinvale irrigation district section e",
  "rochester",
  "rochester west",
  "rochford",
  "rockbank",
  "rocklands",
  "rocklyn",
  "rocky point",
  "rodborough",
  "rokeby",
  "rokewood",
  "rokewood junction",
  "romsey",
  "rosanna",
  "rose river",
  "rosebery",
  "rosebrook",
  "rosebud",
  "rosebud plaza",
  "rosebud west",
  "rosedale",
  "roses gap",
  "rosewhite",
  "roslynmead",
  "ross creek",
  "rossbridge",
  "rostron",
  "rowsley",
  "rowville",
  "roxburgh park",
  "royal melbourne hospital",
  "rubicon",
  "ruby",
  "ruffy",
  "rumbug",
  "running creek",
  "runnymede",
  "rupanyup",
  "rushworth",
  "russells bridge",
  "rutherglen",
  "ryans",
  "ryanston",
  "rye",
  "rythdale",
  "safety beach",
  "sailors falls",
  "sailors gully",
  "sailors hill",
  "saint helena",
  "sale",
  "sale east raaf",
  "sale north",
  "salisbury west",
  "samaria",
  "san remo",
  "sandford",
  "sandhill lake",
  "sandhurst",
  "sandhurst east",
  "sandon",
  "sandown village",
  "sandringham",
  "sandy creek",
  "sandy point",
  "sargood",
  "sarsfield",
  "sassafras",
  "sassafras gully",
  "sawmill settlement",
  "scarsdale",
  "scoresby",
  "scotchmans lead",
  "scotsburn",
  "scotsmans lead",
  "scotts creek",
  "sea lake",
  "seabrook",
  "seacombe",
  "seaford",
  "seaholme",
  "seaspray",
  "seaton",
  "seaview",
  "sebastian",
  "sebastopol",
  "seddon",
  "seddon west",
  "sedgwick",
  "selby",
  "selwyn",
  "separation creek",
  "serpentine",
  "serviceton",
  "seville",
  "seville east",
  "seymour",
  "seymour south",
  "shady creek",
  "shallow inlet",
  "shannonvale",
  "shays flat",
  "she oaks",
  "sheans creek",
  "sheep hills",
  "shelbourne",
  "shelford",
  "shelley",
  "shepherds flat",
  "shepparton",
  "shepparton east",
  "shepparton north",
  "shepparton south",
  "sherbrooke",
  "shirley",
  "shoreham",
  "sidonia",
  "silvan",
  "silver creek",
  "silverleaves",
  "simmie",
  "simpson",
  "simpsons creek",
  "simson",
  "skenes creek",
  "skenes creek north",
  "skibo",
  "skinners flat",
  "skipton",
  "skye",
  "slaty creek",
  "smeaton",
  "smiths beach",
  "smiths gully",
  "smokey town",
  "smokeytown",
  "smoko",
  "smythes creek",
  "smythesdale",
  "snake island",
  "snake valley",
  "soldiers hill",
  "somers",
  "somerton",
  "somerton park",
  "somerville",
  "sorrento",
  "south dudley",
  "south geelong",
  "south kingsville",
  "south kinypanial",
  "south melbourne",
  "south morang",
  "south purrumbete",
  "south wharf",
  "south yarra",
  "southbank",
  "southern cross",
  "southland centre",
  "sovereign hill",
  "spargo creek",
  "specimen hill",
  "speed",
  "speewa",
  "spotswood",
  "spring gully",
  "spring hill",
  "springbank",
  "springdallah",
  "springfield",
  "springhurst",
  "springmount",
  "springvale",
  "springvale south",
  "st albans",
  "st albans park",
  "st andrews beach",
  "st arnaud",
  "st arnaud east",
  "st arnaud north",
  "st clair",
  "st germains",
  "st helena",
  "st helens",
  "st helens plains",
  "st helier",
  "st james",
  "st kilda",
  "st kilda east",
  "st kilda road central",
  "st kilda road melbourne",
  "st kilda south",
  "st kilda west",
  "st leonards",
  "staceys bridge",
  "staffordshire reef",
  "staghorn flat",
  "stanhope",
  "stanhope south",
  "stanley",
  "staughton vale",
  "stavely",
  "stawell",
  "stawell west",
  "steels creek",
  "steiglitz",
  "stewarton",
  "stirling",
  "stockdale",
  "stockyard hill",
  "stonehaven",
  "stoneleigh",
  "stony creek",
  "stonyford",
  "stradbroke",
  "stradbroke park",
  "strangways",
  "straten",
  "stratford",
  "strath creek",
  "strathallan",
  "strathbogie",
  "strathdale",
  "strathdownie",
  "strathewen",
  "strathfieldsaye",
  "strathkellar",
  "strathlea",
  "strathmerton",
  "strathmore",
  "strathmore heights",
  "strathtulloh",
  "streatham",
  "strzelecki",
  "stuart mill",
  "studfield",
  "sugarloaf",
  "sugarloaf creek",
  "suggan buggan",
  "sulky",
  "summerfield",
  "summerlands",
  "sumner",
  "sunbury",
  "sunday creek",
  "sunderland bay",
  "sunnycliffs",
  "sunset strip",
  "sunshine",
  "sunshine north",
  "sunshine west",
  "surf beach",
  "surrey hills",
  "surrey hills north",
  "surrey hills south",
  "sutherland",
  "sutherlands creek",
  "sutton",
  "sutton grange",
  "swan bay",
  "swan hill",
  "swan hill pioneer",
  "swan hill west",
  "swan island",
  "swan marsh",
  "swan reach",
  "swanpool",
  "swanwater",
  "swanwater west",
  "swifts creek",
  "sydenham",
  "sylvaterre",
  "sylvester",
  "syndal",
  "tabberabbera",
  "tabilk",
  "tabor",
  "taggerty",
  "tahara",
  "tahara bridge",
  "tahara west",
  "talbot",
  "talgarno",
  "tallandoon",
  "tallangatta",
  "tallangatta east",
  "tallangatta south",
  "tallangatta valley",
  "tallarook",
  "tallygaroopna",
  "tambo crossing",
  "tambo upper",
  "tamboon",
  "tamboritha",
  "taminick",
  "tamleugh",
  "tamleugh north",
  "tamleugh west",
  "tandarook",
  "tandarra",
  "tangambalanga",
  "tanjil",
  "tanjil bren",
  "tanjil south",
  "tankerton",
  "tantaraboo",
  "tanwood",
  "tanybryn",
  "taradale",
  "tarago",
  "tarcombe",
  "tarilta",
  "taripta",
  "tarnagulla",
  "tarneit",
  "tarnook",
  "taroon",
  "tarra valley",
  "tarranyurk",
  "tarraville",
  "tarrawarra",
  "tarrawingee",
  "tarrayoukyan",
  "tarrengower",
  "tarrenlea",
  "tarrington",
  "tarrone",
  "tarwin",
  "tarwin east",
  "tarwin lower",
  "tatong",
  "tatura",
  "tatura east",
  "tatyoon",
  "tawonga",
  "tawonga south",
  "taylor bay",
  "taylors hill",
  "taylors lakes",
  "teal point",
  "tecoma",
  "teddywaddy",
  "teddywaddy west",
  "teesdale",
  "telangatuk east",
  "telford",
  "telopea downs",
  "templestowe",
  "templestowe lower",
  "tempy",
  "tenby point",
  "tennyson",
  "terang",
  "terip terip",
  "terrappee",
  "terrick terrick",
  "terrick terrick east",
  "tesbury",
  "tetoora road",
  "thalia",
  "thalloo",
  "thaloo",
  "the basin",
  "the cove",
  "the fingerboard",
  "the gurdies",
  "the heart",
  "the honeysuckles",
  "the patch",
  "the pines",
  "the settlement",
  "the sisters",
  "thologolong",
  "thomastown",
  "thomson",
  "thoona",
  "thornbury",
  "thornhill park",
  "thornton",
  "thorpdale",
  "thorpdale south",
  "thowgla valley",
  "three bridges",
  "tidal river",
  "timbarra",
  "timboon",
  "timboon west",
  "timmering",
  "timor",
  "timor west",
  "tinamba",
  "tinamba west",
  "tintaldra",
  "tittybong",
  "titybong",
  "tol tol",
  "tolmie",
  "tom groggin",
  "tongala",
  "tonghi creek",
  "tongio",
  "tonimbuk",
  "tooan",
  "tooborac",
  "toolamba",
  "toolamba west",
  "toolangi",
  "toolern vale",
  "toolleen",
  "toolome",
  "toolondo",
  "toolong",
  "toombon",
  "toongabbie",
  "toora",
  "toora north",
  "tooradin",
  "toorak",
  "toorloo arm",
  "tooronga",
  "toorongo",
  "tootgarook",
  "torquay",
  "torrita",
  "torrumbarry",
  "torwood",
  "tostaree",
  "tottenham",
  "tottington",
  "tourello",
  "towan",
  "towaninny",
  "towaninny south",
  "tower hill",
  "towong",
  "towong upper",
  "trafalgar",
  "trafalgar east",
  "trafalgar south",
  "tragowel",
  "traralgon",
  "traralgon east",
  "traralgon south",
  "travancore",
  "trawalla",
  "trawool",
  "traynors lagoon",
  "tremont",
  "trentham",
  "trentham east",
  "tresco",
  "tresco west",
  "trida",
  "truganina",
  "tubbut",
  "tuerong",
  "tulkara",
  "tullamarine",
  "tungamah",
  "turoar",
  "turriff",
  "turriff east",
  "turtons creek",
  "tutye",
  "tyaak",
  "tyabb",
  "tyenna",
  "tyers",
  "tylden",
  "tylden south",
  "tynong",
  "tynong north",
  "tyntynder",
  "tyntynder south",
  "tyrendarra",
  "tyrendarra east",
  "tyrrell",
  "tyrrell downs",
  "tysons reef",
  "ullina",
  "ullswater",
  "ultima",
  "ultima east",
  "ulupna",
  "undera",
  "underbool",
  "university of melbourne",
  "uplands",
  "upotipotpon",
  "upper ferntree gully",
  "upper gundowring",
  "upper lurg",
  "upper plenty",
  "upper ryans creek",
  "upton hill",
  "upwey",
  "valencia creek",
  "vasey",
  "vaughan",
  "vectis",
  "ventnor",
  "venus bay",
  "vermont",
  "vermont south",
  "vervale",
  "vesper",
  "victoria gardens",
  "victoria point",
  "victoria valley",
  "viewbank",
  "vinifera",
  "violet town",
  "vite vite",
  "vite vite north",
  "w tree",
  "waaia",
  "waanyarra",
  "waarre",
  "wabonga",
  "waggarandall",
  "wahgunyah",
  "wahring",
  "wail",
  "wairewa",
  "waitchie",
  "wal wal",
  "waldara",
  "walhalla",
  "walhalla east",
  "walkerville",
  "walkerville north",
  "walkerville south",
  "wallace",
  "wallacedale",
  "wallagaraugh",
  "wallaloo",
  "wallaloo east",
  "wallan",
  "wallan east",
  "wallinduc",
  "wallington",
  "wallup",
  "walmer",
  "walpa",
  "walpeup",
  "walwa",
  "wanalta",
  "wandana heights",
  "wandella",
  "wandiligong",
  "wandin east",
  "wandin north",
  "wando bridge",
  "wando vale",
  "wandong",
  "wandown",
  "wangandary",
  "wangarabell",
  "wangaratta",
  "wangaratta forward",
  "wangaratta south",
  "wangaratta west",
  "wangie",
  "wangoom",
  "wannon",
  "wantirna",
  "wantirna south",
  "waranga",
  "waranga shores",
  "waratah bay",
  "waratah north",
  "warburton",
  "wareek",
  "wargan",
  "warmur",
  "warncoort",
  "warne",
  "warneet",
  "warrabkook",
  "warracknabeal",
  "warragul",
  "warragul south",
  "warragul west",
  "warrak",
  "warrandyte",
  "warrandyte south",
  "warranwood",
  "warrayure",
  "warrenbayne",
  "warrenheip",
  "warrenmang",
  "warrion",
  "warrnambool",
  "warrnambool east",
  "warrnambool west",
  "warrock",
  "warrong",
  "wartook",
  "watchem",
  "watchem west",
  "watchupga",
  "waterford",
  "waterford park",
  "watergardens",
  "waterholes",
  "waterloo",
  "waterways",
  "watgania",
  "watsonia",
  "watsonia north",
  "watsons creek",
  "wattle bank",
  "wattle creek",
  "wattle flat",
  "wattle glen",
  "wattle hill",
  "wattle park",
  "wattville",
  "waubra",
  "waurn ponds",
  "waverley gardens",
  "waygara",
  "weatherboard",
  "wedderburn",
  "wedderburn junction",
  "wee wee rup",
  "weeaproinah",
  "weeragua",
  "weering",
  "weerite",
  "wehla",
  "weir views",
  "wellsford",
  "welshmans reef",
  "welshpool",
  "wemen",
  "wendouree",
  "wendouree village",
  "wensleydale",
  "wentworth",
  "werneth",
  "werona",
  "werribee",
  "werribee south",
  "werrimull",
  "wesburn",
  "west bendigo",
  "west creek",
  "west footscray",
  "west melbourne",
  "west wodonga",
  "westbury",
  "westby",
  "westmeadows",
  "westmere",
  "whanregarwen",
  "wharparilla",
  "wheatsheaf",
  "wheelers hill",
  "whipstick",
  "whirily",
  "white hills",
  "whiteheads creek",
  "whitelaw",
  "whitfield",
  "whitlands",
  "whittington",
  "whittlesea",
  "whoorel",
  "whorouly",
  "whorouly east",
  "whorouly south",
  "whroo",
  "wickliffe",
  "wilby",
  "wild dog valley",
  "wildwood",
  "wilkur",
  "willangie",
  "willatook",
  "willaura",
  "willaura north",
  "willenabrina",
  "williams landing",
  "williams raaf",
  "williamstown",
  "williamstown north",
  "willow grove",
  "willowmavin",
  "willowvale",
  "willung",
  "willung south",
  "wilsons hill",
  "wilsons promontory",
  "wimbledon heights",
  "winchelsea",
  "winchelsea south",
  "windermere",
  "windsor",
  "wingan river",
  "wingeel",
  "winjallok",
  "winlaton",
  "winnambool",
  "winnap",
  "winnindoo",
  "winslow",
  "winter valley",
  "winton",
  "winton north",
  "wirrate",
  "wiseleigh",
  "wishart",
  "wodonga",
  "wodonga forward",
  "wodonga plaza",
  "wollert",
  "wombat creek",
  "wombelano",
  "won wron",
  "wonga",
  "wonga park",
  "wongarra",
  "wongungarra",
  "wonnangatta",
  "wonthaggi",
  "wonwondah",
  "wonwondah east",
  "wonwondah south",
  "wonyip",
  "wood wood",
  "woodbrook",
  "woodend",
  "woodend north",
  "woodfield",
  "woodford",
  "woodglen",
  "woodhouse",
  "woodleigh",
  "woods point",
  "woodside",
  "woodside beach",
  "woodside north",
  "woodstock",
  "woodstock on loddon",
  "woodstock west",
  "woodvale",
  "woohlpooer",
  "wool wool",
  "woolamai",
  "woolenook",
  "woolshed",
  "woolshed flat",
  "woolsthorpe",
  "woomelang",
  "wooragee",
  "woorarra",
  "woorarra east",
  "woorarra west",
  "wooreen",
  "woori yallock",
  "woorinen",
  "woorinen north",
  "woorinen south",
  "woorndoo",
  "wooroonook",
  "woosang",
  "wootong vale",
  "world trade centre",
  "worrowing",
  "wrathung",
  "wrixon",
  "wroxham",
  "wuk wuk",
  "wulgulmerang",
  "wulgulmerang east",
  "wulgulmerang west",
  "wunghnu",
  "wurdiboluc",
  "wurruk",
  "wy yung",
  "wycheproof",
  "wycheproof south",
  "wychitella",
  "wychitella north",
  "wye river",
  "wyelangta",
  "wyndham vale",
  "wyuna",
  "wyuna east",
  "yaapeet",
  "yabba north",
  "yabba south",
  "yackandandah",
  "yalca",
  "yalla y poora",
  "yallambie",
  "yallook",
  "yallourn",
  "yallourn north",
  "yalmy",
  "yambuk",
  "yambuna",
  "yan yean",
  "yanac",
  "yanakie",
  "yando",
  "yandoit",
  "yandoit hills",
  "yangery",
  "yangoura",
  "yannathan",
  "yapeen",
  "yarck",
  "yarpturk",
  "yarra glen",
  "yarra junction",
  "yarraberb",
  "yarragon",
  "yarragon south",
  "yarram",
  "yarrambat",
  "yarraville",
  "yarraville west",
  "yarrawalla",
  "yarrawonga",
  "yarrawonga south",
  "yarrowee",
  "yarroweyah",
  "yarrunga",
  "yarto",
  "yatchaw",
  "yawong hills",
  "yea",
  "yellingbo",
  "yelta",
  "yendon",
  "yeo",
  "yeodene",
  "yering",
  "yeungroon",
  "yeungroon east",
  "yielima",
  "yinnar",
  "yinnar south",
  "york plains",
  "youanmite",
  "youarang",
  "yulecart",
  "yundool",
  "yuroke",
  "yuulong",
  "zeerust",
  "zumsteins",
]);

/**
 * Victorian locality names that also name a locality in another state —
 * Richmond, Brighton, St Kilda, Preston. 457 entries.
 *
 * Naming one of these is not evidence of being in Victoria, so the agent layer
 * requires corroboration (an explicit state, a postcode, or a geolocation fix)
 * before routing the turn to the Victorian MCP. Serving Victorian directory
 * links to someone in Richmond NSW is the failure spec §4 exists to prevent.
 */
export const CROSS_STATE_LOCALITIES: ReadonlySet<string> = new Set([
  "abbotsford",
  "airly",
  "albert park",
  "alberton",
  "albion",
  "alexandra",
  "alma",
  "altona",
  "anakie",
  "apollo bay",
  "appin",
  "apsley",
  "arcadia",
  "argyle",
  "armadale",
  "armstrong creek",
  "arnold",
  "ascot",
  "ashbourne",
  "auburn",
  "auburn south",
  "avalon",
  "avoca",
  "balaclava",
  "bald hills",
  "balmoral",
  "bannockburn",
  "barkly",
  "basalt",
  "baw baw",
  "baynton",
  "bayswater",
  "beaconsfield",
  "beaufort",
  "beaumaris",
  "bellfield",
  "belmont",
  "berrambool",
  "beulah",
  "big hill",
  "black hill",
  "black range",
  "black rock",
  "blackheath",
  "blackwood",
  "bolwarra",
  "bona vista",
  "bonnie doon",
  "bonshaw",
  "boonah",
  "box hill",
  "brandy creek",
  "bridgewater",
  "bright",
  "brighton",
  "broadmeadows",
  "broadwater",
  "brookfield",
  "brooklyn",
  "broughton",
  "brown hill",
  "browns plains",
  "brunswick",
  "buckland",
  "budgee budgee",
  "buffalo creek",
  "bulga",
  "bulla",
  "bundoora",
  "bungaree",
  "bungil",
  "burnside",
  "burwood",
  "burwood heights",
  "bushy park",
  "buxton",
  "cabarita",
  "camberwell",
  "campbelltown",
  "camperdown",
  "canterbury",
  "carina",
  "carlton",
  "cassilis",
  "castle creek",
  "cathcart",
  "charlton",
  "chatsworth",
  "cheltenham",
  "childers",
  "christmas hills",
  "churchill",
  "clarendon",
  "clayton",
  "clifton hill",
  "clunes",
  "clyde",
  "clydesdale",
  "cockatoo",
  "codrington",
  "coldstream",
  "collingwood",
  "cooma",
  "coopers creek",
  "corinella",
  "corndale",
  "cosgrove",
  "craigie",
  "cremorne",
  "cressy",
  "cromer",
  "cross roads",
  "croydon",
  "crystal creek",
  "curlewis",
  "daisy hill",
  "darlington",
  "dartmoor",
  "dawson",
  "deepdene",
  "derby",
  "dixie",
  "donnybrook",
  "douglas",
  "dunkeld",
  "dunolly",
  "dunrobin",
  "dysart",
  "eastwood",
  "ellerslie",
  "elphinstone",
  "eltham",
  "emerald",
  "emu creek",
  "emu flat",
  "enfield",
  "epping",
  "epsom",
  "eskdale",
  "eureka",
  "fairfield",
  "falls creek",
  "ferguson",
  "ferndale",
  "fernvale",
  "fingal",
  "fitzroy",
  "five ways",
  "flinders",
  "flowerdale",
  "flynn",
  "forbes",
  "forest hill",
  "forrest",
  "fulham",
  "garfield",
  "georges creek",
  "germantown",
  "gilberton",
  "gladfield",
  "glen iris",
  "glengarry",
  "glenlee",
  "glenlyon",
  "glenmore",
  "glenorchy",
  "glenroy",
  "golden beach",
  "goldsborough",
  "gordon",
  "grassdale",
  "green gully",
  "greendale",
  "greenhill",
  "greens creek",
  "greenvale",
  "greta",
  "guildford",
  "hamilton",
  "hampton",
  "hanging rock",
  "happy valley",
  "hastings",
  "havilah",
  "hawthorn",
  "heathcote",
  "heathwood",
  "henty",
  "herne hill",
  "hexham",
  "hidden valley",
  "hill end",
  "hillcrest",
  "hillside",
  "homebush",
  "hopetoun",
  "huntingdale",
  "inglewood",
  "inkerman",
  "invergordon",
  "invermay",
  "iona",
  "irishtown",
  "ironbark",
  "irymple",
  "ivanhoe",
  "jamieson",
  "jericho",
  "kangaroo flat",
  "kenmare",
  "kensington",
  "kew",
  "kialla",
  "killara",
  "killarney",
  "killawarra",
  "killingworth",
  "kimbolton",
  "kings park",
  "kingston",
  "kulwin",
  "landsborough",
  "langley",
  "laverton",
  "lawrence",
  "learmonth",
  "leigh creek",
  "lillico",
  "lilydale",
  "limestone",
  "lismore",
  "little river",
  "locksley",
  "lone pine",
  "longford",
  "longwood",
  "lorne",
  "lucknow",
  "lyndhurst",
  "lyons",
  "macarthur",
  "macclesfield",
  "macleod",
  "maffra",
  "maldon",
  "malvern",
  "mangalore",
  "mansfield",
  "marengo",
  "martins creek",
  "maryborough",
  "maryvale",
  "maude",
  "melton",
  "mia mia",
  "middle park",
  "millbrook",
  "mingay",
  "minto",
  "mitcham",
  "mitchell park",
  "molesworth",
  "montrose",
  "moora",
  "mornington",
  "mortlake",
  "mosquito creek",
  "mount mitchell",
  "mount pleasant",
  "mountain view",
  "mulgrave",
  "murchison",
  "murphys creek",
  "myola",
  "myrtle creek",
  "narrung",
  "nelson",
  "netherby",
  "newbridge",
  "newington",
  "newport",
  "newstead",
  "newtown",
  "nicholson",
  "nine mile",
  "normanville",
  "north shore",
  "northwood",
  "nyora",
  "olinda",
  "orford",
  "oxley",
  "panitya",
  "paradise",
  "paradise beach",
  "parkville",
  "parkwood",
  "paynesville",
  "penshurst",
  "peterborough",
  "pheasant creek",
  "pine grove",
  "pine lodge",
  "pine mountain",
  "plenty",
  "plumpton",
  "portland",
  "prairie",
  "preston",
  "queenscliff",
  "raglan",
  "ravenswood",
  "red hill",
  "redbank",
  "reedy creek",
  "reefton",
  "reservoir",
  "richmond",
  "ringwood",
  "riverside",
  "robinson",
  "rochester",
  "rocky point",
  "rokeby",
  "rosebery",
  "rosebrook",
  "rosedale",
  "ross creek",
  "running creek",
  "runnymede",
  "safety beach",
  "san remo",
  "sandford",
  "sandon",
  "sandringham",
  "sandy creek",
  "sandy point",
  "sassafras",
  "scotts creek",
  "seabrook",
  "seaford",
  "seaton",
  "sebastopol",
  "seddon",
  "selwyn",
  "serpentine",
  "serviceton",
  "seymour",
  "shannonvale",
  "shelley",
  "silver creek",
  "simmie",
  "simpson",
  "skye",
  "soldiers hill",
  "somerton",
  "somerton park",
  "somerville",
  "sorrento",
  "southern cross",
  "speewa",
  "spring gully",
  "spring hill",
  "springfield",
  "springvale",
  "st albans",
  "st clair",
  "st helena",
  "st helens",
  "st james",
  "st kilda",
  "st leonards",
  "stanhope",
  "stanley",
  "steiglitz",
  "stewarton",
  "stirling",
  "stoneleigh",
  "stony creek",
  "stratford",
  "strathmore",
  "strzelecki",
  "sugarloaf",
  "sumner",
  "sunset strip",
  "sunshine",
  "surf beach",
  "sutherland",
  "sutton",
  "swan bay",
  "swan reach",
  "sydenham",
  "talbot",
  "taradale",
  "tarago",
  "tarrawarra",
  "teesdale",
  "tennyson",
  "the basin",
  "the pines",
  "thornton",
  "timbarra",
  "timor",
  "toongabbie",
  "toora",
  "torquay",
  "torwood",
  "tottenham",
  "trafalgar",
  "trida",
  "tyenna",
  "ventnor",
  "venus bay",
  "victoria point",
  "victoria valley",
  "walkerville",
  "walmer",
  "wandella",
  "wangaratta",
  "warburton",
  "waterford",
  "waterloo",
  "watsons creek",
  "wattle flat",
  "wattle hill",
  "wattle park",
  "wedderburn",
  "welshpool",
  "wentworth",
  "westbury",
  "westby",
  "white hills",
  "whitfield",
  "wild dog valley",
  "williamstown",
  "willowvale",
  "windermere",
  "windsor",
  "winton",
  "wishart",
  "wombat creek",
  "wonga",
  "woodend",
  "woodford",
  "woodleigh",
  "woods point",
  "woodside",
  "woodstock",
  "woodvale",
  "woolshed",
  "woolshed flat",
  "wyuna",
  "yallambie",
  "yarrawonga",
  "yarrunga",
  "yelta",
  "york plains",
]);

/**
 * Word count of the longest Victorian locality name ("bell bird creek east" and
 * friends). Bounds the sliding window the message-extractor tries.
 */
export const MAX_LOCALITY_WORDS = 5;
